### PR TITLE
Fix MutRange[T] problems.

### PR DESCRIPTION
**Pull request by cheatfate**

### CODE REVIEW

**Comment by arnetheduck** [comment]
would be nice with a test to understand better what this is about

**Comment by cheatfate** [comment]
@arnetheduck there was compilation problem where `advance` procedures got used. Some unusual type interference with `converter` hiding real error message.

**Comment by arnetheduck** [comment]
yeah, though a test would guard more permanently against a similar mistake

**Comment by yglukhov** [comment]
Addressed in #28

**Pull request merged**
